.gitignore
SeniorDesign-Group9/pcb pull request #12
Opened 2023-02-16 01:31 UTC by myhe01

2023-02-16 04:14 UTC, NChitty requested changes
I don't think we want to exclude the PrjPcbStructure as I don't know it's function but I know it changes with the project

2023-02-16 15:33 UTC, myhe01 commented
@NChitty I've had them under .gitignore on my branches and it hasn't really changed anything, but I'm really not that committed on having it under .gitignore.

2023-02-17 19:32 UTC, myhe01 commented
@NChitty Still need a review on this.

2023-02-17 20:19 UTC, NChitty approved these changes

2023-02-21 01:24 UTC, merged